gui:
  theme:
    selectedLineBgColor:
      - "#414868" # set to `default` to have no background colour
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  showFileIcons: true # for hiding file icons in the file views
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    # externalDiffCommand: difft --color=always
